#!/usr/bin/env node
/**
 * 从高德 Web 服务 API 拉取成都核心区 POI，并生成 scenic_spot / scenic_feature / route_edge SQL。
 *
 * 使用方式：
 *   $env:AMAP_KEY="你的高德Web服务Key"
 *   node database/amap_fetch_generate.mjs
 *
 * 输出：
 *   database/generated/amap_raw_poi.json
 *   database/generated/amap_scenic_spot.sql
 *   database/generated/amap_route_edge.sql
 *   database/generated/amap_all.sql
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const AMAP_KEY = process.env.AMAP_KEY || process.env.GAODE_KEY;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "database", "generated");

const SEARCH_URL = "https://restapi.amap.com/v3/place/text";
const DRIVING_URL = "https://restapi.amap.com/v3/direction/driving";
const WALKING_URL = "https://restapi.amap.com/v3/direction/walking";

const DISTRICTS = [
  { name: "锦江区", adcode: "510104" },
  { name: "青羊区", adcode: "510105" },
  { name: "金牛区", adcode: "510106" },
  { name: "武侯区", adcode: "510107" },
  { name: "成华区", adcode: "510108" },
];

const SEARCH_TASKS = [
  { keyword: "景点", category: "景点", recovery: false },
  { keyword: "博物馆", category: "博物馆", recovery: false },
  { keyword: "历史文化", category: "历史文化", recovery: false },
  { keyword: "美食街", category: "美食街区", recovery: false },
  { keyword: "商圈", category: "休闲商圈", recovery: true },
  { keyword: "公园", category: "公园休闲", recovery: true },
  { keyword: "茶馆", category: "茶馆休息", recovery: true },
  { keyword: "咖啡", category: "咖啡休息", recovery: true },
];

const MAX_POIS = Number(process.env.AMAP_MAX_POIS || 40);
const ROUTE_NODE_LIMIT = Number(process.env.AMAP_ROUTE_NODE_LIMIT || 25);
const PAGE_LIMIT = Number(process.env.AMAP_PAGE_LIMIT || 1);
const REQUEST_DELAY_MS = Number(process.env.AMAP_REQUEST_DELAY_MS || 1000);
const ROUTE_DELAY_MS = Number(process.env.AMAP_ROUTE_DELAY_MS || 1200);
const MAX_RETRY = Number(process.env.AMAP_MAX_RETRY || 6);

if (!AMAP_KEY) {
  console.error("缺少 AMAP_KEY。请先设置环境变量，例如：$env:AMAP_KEY=\"你的高德Web服务Key\"");
  process.exit(1);
}

await fs.mkdir(OUT_DIR, { recursive: true });

const pois = await fetchPois();
const selected = selectPois(pois, MAX_POIS);
const routeEdges = await fetchRouteEdges(selected.slice(0, ROUTE_NODE_LIMIT));

await fs.writeFile(path.join(OUT_DIR, "amap_raw_poi.json"), JSON.stringify(selected, null, 2), "utf8");

const spotSql = buildSpotSql(selected);
const routeSql = buildRouteSql(routeEdges);
const allSql = [
  "-- Auto-generated by database/amap_fetch_generate.mjs",
  "-- Data source: Amap Web Service API",
  "USE personalized_travel;",
  spotSql,
  routeSql,
].join("\n\n");

await fs.writeFile(path.join(OUT_DIR, "amap_scenic_spot.sql"), spotSql, "utf8");
await fs.writeFile(path.join(OUT_DIR, "amap_route_edge.sql"), routeSql, "utf8");
await fs.writeFile(path.join(OUT_DIR, "amap_all.sql"), allSql, "utf8");

console.log(`已生成 ${selected.length} 个 scenic_spot/scenic_feature POI。`);
console.log(`已生成 ${routeEdges.length} 条 route_edge。`);
console.log(`输出目录：${OUT_DIR}`);

async function fetchPois() {
  const results = [];
  for (const district of DISTRICTS) {
    for (const task of SEARCH_TASKS) {
      for (let page = 1; page <= PAGE_LIMIT; page += 1) {
        const url = new URL(SEARCH_URL);
        url.searchParams.set("key", AMAP_KEY);
        url.searchParams.set("keywords", task.keyword);
        url.searchParams.set("city", district.adcode);
        url.searchParams.set("citylimit", "true");
        url.searchParams.set("offset", "25");
        url.searchParams.set("page", String(page));
        url.searchParams.set("extensions", "all");
        url.searchParams.set("output", "JSON");

        const body = await amapGet(url);
        const pagePois = Array.isArray(body.pois) ? body.pois : [];
        for (const poi of pagePois) {
          if (!poi.location || !poi.name) continue;
          results.push(normalizePoi(poi, district, task));
        }
        await sleep(REQUEST_DELAY_MS);
        if (pagePois.length < 25) break;
      }
    }
  }
  return results;
}

function selectPois(pois, limit) {
  const byKey = new Map();
  for (const poi of pois) {
    const key = poi.sourcePoiId || `${poi.name}-${poi.location}`;
    const old = byKey.get(key);
    if (!old || poi.score > old.score) {
      byKey.set(key, poi);
    }
  }
  return [...byKey.values()]
    .filter((poi) => poi.city === "成都市" || poi.city === "成都" || poi.adname)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((poi, index) => ({ ...poi, localId: index + 1 }));
}

function normalizePoi(poi, district, task) {
  const [longitude, latitude] = String(poi.location).split(",").map(Number);
  const typeText = [poi.type, poi.typecode, task.keyword, poi.name].filter(Boolean).join(" ");
  const recovery = task.recovery || /公园|茶|咖啡|休闲|商场|购物中心|广场/.test(typeText);
  const category = inferCategory(poi, task);
  const scores = inferFeatureScores({ ...poi, category, recovery });
  const popularity = inferPopularity(poi, recovery);
  return {
    sourceName: "amap",
    sourcePoiId: poi.id || "",
    name: poi.name,
    city: poi.cityname || "成都",
    district: poi.adname || district.name,
    adcode: poi.adcode || district.adcode,
    address: normalizeAddress(poi.address),
    longitude,
    latitude,
    location: `${longitude},${latitude}`,
    category,
    ticketPrice: inferTicketPrice(category, poi.name),
    stayDuration: inferStayDuration(category, recovery),
    openTime: inferOpenTime(category, recovery),
    closeTime: inferCloseTime(category, recovery),
    popularity,
    description: buildDescription(poi, category, recovery),
    isRecoveryNode: recovery,
    imageUrl: "",
    score: popularity + (recovery ? 6 : 0) + scores.historyScore + scores.foodScore + scores.leisureScore,
    raw: poi,
    ...scores,
  };
}

async function fetchRouteEdges(spots) {
  const edges = [];
  for (let i = 0; i < spots.length; i += 1) {
    const distances = spots
      .map((spot, index) => ({
        index,
        minutes: i === index ? Infinity : roughMinutes(spots[i], spot),
      }))
      .filter((item) => item.index !== i)
      .sort((a, b) => a.minutes - b.minutes)
      .slice(0, 4);

    for (const item of distances) {
      const from = spots[i];
      const to = spots[item.index];
      const edge = await fetchOneRoute(from, to);
      edges.push(edge);
      await sleep(ROUTE_DELAY_MS);
    }
  }
  return dedupeEdges(edges);
}

async function fetchOneRoute(from, to) {
  const rough = roughMinutes(from, to);
  const mode = rough <= 18 ? "walk" : "taxi";
  const url = new URL(mode === "walk" ? WALKING_URL : DRIVING_URL);
  url.searchParams.set("key", AMAP_KEY);
  url.searchParams.set("origin", from.location);
  url.searchParams.set("destination", to.location);
  url.searchParams.set("output", "JSON");

  try {
    const body = await amapGet(url);
    const path0 = body.route?.paths?.[0];
    if (path0) {
      return {
        fromId: from.localId,
        toId: to.localId,
        distance: metersToKm(Number(path0.distance || 0)),
        travelTime: Math.max(1, Math.round(Number(path0.duration || 0) / 60)),
        travelCost: mode === "walk" ? 0 : taxiCost(Number(path0.distance || 0)),
        transportMode: mode,
      };
    }
  } catch (error) {
    console.warn(`路径获取失败，使用估算：${from.name} -> ${to.name}，${error.message}`);
  }

  return {
    fromId: from.localId,
    toId: to.localId,
    distance: metersToKm(roughDistanceMeters(from, to)),
    travelTime: rough,
    travelCost: mode === "walk" ? 0 : taxiCost(roughDistanceMeters(from, to)),
    transportMode: mode,
  };
}

async function amapGet(url) {
  for (let attempt = 0; attempt <= MAX_RETRY; attempt += 1) {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    const body = await response.json();
    if (body.status === "1") {
      return body;
    }
    const info = `${body.info || "AMAP_ERROR"} ${body.infocode || ""}`.trim();
    if (body.infocode === "10021" && attempt < MAX_RETRY) {
      const waitMs = REQUEST_DELAY_MS * (attempt + 2) * 2;
      console.warn(`高德接口限流，等待 ${waitMs}ms 后重试...`);
      await sleep(waitMs);
      continue;
    }
    throw new Error(info);
  }
  throw new Error("AMAP_RETRY_EXHAUSTED");
}

function buildSpotSql(spots) {
  const spotRows = spots.map((poi) => `(${[
    poi.localId,
    q(poi.name),
    q("成都"),
    q(poi.district),
    q(poi.address),
    fixed(poi.longitude, 6),
    fixed(poi.latitude, 6),
    q(poi.category),
    fixed(poi.ticketPrice, 2),
    poi.stayDuration,
    q(poi.openTime),
    q(poi.closeTime),
    fixed(poi.popularity, 2),
    q(poi.description),
    poi.isRecoveryNode ? 1 : 0,
    q(poi.imageUrl),
  ].join(", ")})`);

  const featureRows = spots.map((poi) => `(${[
    poi.localId,
    fixed(poi.historyScore, 2),
    fixed(poi.foodScore, 2),
    fixed(poi.natureScore, 2),
    fixed(poi.shoppingScore, 2),
    fixed(poi.leisureScore, 2),
    fixed(poi.photoScore, 2),
    fixed(poi.physicalLoad, 2),
    fixed(poi.cognitiveLoad, 2),
    fixed(poi.crowdLoad, 2),
    fixed(poi.queueLoad, 2),
    fixed(poi.recoveryValue, 2),
    q(poi.tags),
  ].join(", ")})`);

  const rawRows = spots.map((poi) => `(${q("amap")}, ${q(poi.sourcePoiId)}, CAST(${q(JSON.stringify(poi.raw))} AS JSON))`);

  return [
    "SET FOREIGN_KEY_CHECKS = 0;",
    "TRUNCATE TABLE travel_plan_detail;",
    "TRUNCATE TABLE travel_plan;",
    "TRUNCATE TABLE user_demand;",
    "TRUNCATE TABLE route_edge;",
    "TRUNCATE TABLE scenic_feature;",
    "TRUNCATE TABLE scenic_spot;",
    "TRUNCATE TABLE map_poi_raw;",
    "SET FOREIGN_KEY_CHECKS = 1;",
    "",
    "INSERT INTO map_poi_raw (source_name, source_poi_id, raw_json) VALUES",
    `${rawRows.join(",\n")};`,
    "",
    "INSERT INTO scenic_spot (id, name, city, district, address, longitude, latitude, category, ticket_price, stay_duration, open_time, close_time, popularity, description, is_recovery_node, image_url) VALUES",
    `${spotRows.join(",\n")};`,
    "",
    "INSERT INTO scenic_feature (scenic_id, history_score, food_score, nature_score, shopping_score, leisure_score, photo_score, physical_load, cognitive_load, crowd_load, queue_load, recovery_value, tags) VALUES",
    `${featureRows.join(",\n")};`,
  ].join("\n");
}

function buildRouteSql(edges) {
  const rows = edges.map((edge) => `(${[
    edge.fromId,
    edge.toId,
    fixed(edge.distance, 2),
    edge.travelTime,
    fixed(edge.travelCost, 2),
    q(edge.transportMode),
  ].join(", ")})`);
  return [
    "INSERT INTO route_edge (from_spot_id, to_spot_id, distance, travel_time, travel_cost, transport_mode) VALUES",
    `${rows.join(",\n")};`,
  ].join("\n");
}

function inferCategory(poi, task) {
  const text = [poi.name, poi.type, task.keyword].join(" ");
  if (/博物馆|纪念馆|展览馆/.test(text)) return "博物馆";
  if (/公园|绿地|湿地/.test(text)) return "公园休闲";
  if (/茶|茶馆/.test(text)) return "茶馆休息";
  if (/咖啡|咖啡馆/.test(text)) return "咖啡休息";
  if (/商场|购物|商圈|太古里|春熙/.test(text)) return "休闲商圈";
  if (/美食|小吃|餐饮|火锅|街/.test(text)) return "美食街区";
  if (/寺|祠|遗址|古|历史|文化/.test(text)) return "历史文化";
  if (/艺术|创意|文创/.test(text)) return "艺术街区";
  return task.category || "城市景点";
}

function inferFeatureScores(poi) {
  const text = [poi.name, poi.type, poi.category].join(" ");
  const recovery = poi.recovery;
  const history = /博物馆|纪念馆|遗址|寺|祠|历史|文化|古/.test(text) ? 0.88 : 0.18;
  const food = /美食|餐饮|小吃|火锅|茶|咖啡/.test(text) ? 0.86 : 0.18;
  const nature = /公园|绿地|湿地|河|湖/.test(text) ? 0.86 : 0.12;
  const shopping = /购物|商场|商圈|太古里|春熙/.test(text) ? 0.88 : 0.12;
  const leisure = recovery || /休闲|茶|咖啡|公园|街区/.test(text) ? 0.86 : 0.35;
  const photo = /拍照|观景|艺术|创意|街区|太古里|IFS|熊猫/.test(text) ? 0.82 : 0.55;
  const physical = recovery ? 0.12 : /公园|街区|步行|遗址/.test(text) ? 0.42 : 0.30;
  const cognitive = /博物馆|纪念馆|历史|文化|遗址/.test(text) ? 0.72 : recovery ? 0.10 : 0.30;
  const crowd = /春熙|太古里|宽窄|锦里|商圈|美食|热门/.test(text) ? 0.78 : recovery ? 0.30 : 0.44;
  const queue = /热门|博物馆|锦里|宽窄|春熙|太古里/.test(text) ? 0.40 : recovery ? 0.08 : 0.20;
  const recoveryValue = recovery ? /茶|咖啡/.test(text) ? 0.92 : 0.78 : 0.18;
  const tags = [
    history > 0.7 ? "历史" : null,
    food > 0.7 ? "美食" : null,
    nature > 0.7 ? "自然" : null,
    shopping > 0.7 ? "购物" : null,
    leisure > 0.7 ? "休闲" : null,
    photo > 0.7 ? "拍照" : null,
  ].filter(Boolean).join(",");
  return {
    historyScore: history,
    foodScore: food,
    natureScore: nature,
    shoppingScore: shopping,
    leisureScore: leisure,
    photoScore: photo,
    physicalLoad: physical,
    cognitiveLoad: cognitive,
    crowdLoad: crowd,
    queueLoad: queue,
    recoveryValue,
    tags,
  };
}

function inferPopularity(poi, recovery) {
  const base = recovery ? 76 : 82;
  const biz = poi.biz_ext || {};
  const rating = Number(biz.rating || 0);
  return Math.min(98, Math.max(65, base + (rating ? rating * 3 : 0)));
}

function inferTicketPrice(category, name) {
  if (/博物馆/.test(category) && /金沙/.test(name)) return 70;
  if (/历史文化/.test(category) && /武侯|草堂/.test(name)) return 50;
  if (/观景/.test(category)) return 70;
  return 0;
}

function inferStayDuration(category, recovery) {
  if (recovery) return /茶|咖啡/.test(category) ? 50 : 70;
  if (/博物馆|历史文化/.test(category)) return 130;
  if (/美食|商圈|街区/.test(category)) return 90;
  return 80;
}

function inferOpenTime(category) {
  if (/夜游/.test(category)) return "18:00";
  if (/商圈|美食|咖啡|茶/.test(category)) return "10:00";
  return "09:00";
}

function inferCloseTime(category) {
  if (/夜游|美食/.test(category)) return "23:00";
  if (/商圈|咖啡|茶/.test(category)) return "22:00";
  return "18:00";
}

function buildDescription(poi, category, recovery) {
  if (recovery) return `${poi.name}适合作为${category}，可在路线偏赶时用来放慢节奏。`;
  return `${poi.name}属于${category}，可结合兴趣、预算和当天强度安排进成都路线。`;
}

function normalizeAddress(address) {
  if (Array.isArray(address)) return address.join("");
  return address || "";
}

function dedupeEdges(edges) {
  const map = new Map();
  for (const edge of edges) {
    if (edge.fromId === edge.toId) continue;
    const key = `${edge.fromId}-${edge.toId}-${edge.transportMode}`;
    if (!map.has(key)) map.set(key, edge);
  }
  return [...map.values()];
}

function roughMinutes(a, b) {
  return Math.max(6, Math.round(roughDistanceMeters(a, b) / 1000 / 22 * 60));
}

function roughDistanceMeters(a, b) {
  const dx = (a.longitude - b.longitude) * 96000;
  const dy = (a.latitude - b.latitude) * 111000;
  return Math.sqrt(dx * dx + dy * dy);
}

function metersToKm(meters) {
  return Math.round((meters / 1000) * 100) / 100;
}

function taxiCost(meters) {
  const km = meters / 1000;
  return Math.max(0, Math.round((10 + Math.max(0, km - 2) * 2.2) * 100) / 100);
}

function q(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replaceAll("\\", "\\\\").replaceAll("'", "''")}'`;
}

function fixed(value, digits) {
  return Number(value || 0).toFixed(digits);
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
