#!/usr/bin/env node
/**
 * 生成旅游日记演示数据。
 *
 * 输出：
 * - database/generated/diary_seed_80.sql
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "database", "generated");
const DIARY_COUNT = Number(process.env.DIARY_COUNT || 80);

const destinations = [
  "成都",
  "锦里古街",
  "杜甫草堂",
  "春熙路-太古里商圈",
  "人民公园",
  "明德大学002校区",
  "云锦山001景区",
  "青竹湖003景区",
  "知行学院004校区",
  "花溪谷005景区",
];

const themes = [
  ["历史", "武侯祠", "展陈信息很多，适合上午慢慢看，后面需要安排茶馆或公园缓冲。"],
  ["美食", "建设路小吃街", "小吃选择很多，但排队会增加疲劳，适合放在晚上收尾。"],
  ["休闲", "人民公园", "茶馆、湖边和慢步道能明显降低当天节奏压力。"],
  ["购物", "太古里", "开放街区适合拍照和购物，中途插入咖啡点体验更好。"],
  ["校园", "教学楼", "从教学楼到食堂可以演示距离最短和时间最短两种路线。"],
  ["导航", "洗手间", "附近设施查询按照内部道路距离排序，比直线距离更接近真实体验。"],
  ["自然", "青竹湖", "湖边路线适合慢游，节点密度不要太高。"],
  ["拍照", "东郊记忆", "工业风街区很好拍，但连续走动时间较长，需要控制节奏。"],
];

const images = [
  "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80",
];

await fs.mkdir(OUT_DIR, { recursive: true });

const rows = [];
for (let i = 1; i <= DIARY_COUNT; i += 1) {
  const destination = destinations[i % destinations.length];
  const theme = themes[i % themes.length];
  const secondTheme = themes[(i + 3) % themes.length];
  const title = `${destination}日记 ${String(i).padStart(2, "0")}：${theme[0]}和${secondTheme[0]}体验`;
  const content = [
    `这篇日记记录了在${destination}的游览体验。`,
    `这次重点关注${theme[1]}，${theme[2]}`,
    `路线中还结合了${secondTheme[1]}，${secondTheme[2]}`,
    "系统推荐时会考虑浏览量、评分和兴趣标签；查询时可以按照目的地、标题和正文关键词检索。",
    "如果用于线下演示，可以搜索茶馆、洗手间、食堂、路线、教学楼、拍照、美食等关键词。",
  ].join("");
  const tags = unique([theme[0], secondTheme[0], destination.includes("校区") ? "校园" : "旅行", "路线"]).join(",");
  const compressed = gzipSync(Buffer.from(content, "utf8")).toString("base64");
  rows.push({
    id: i,
    title,
    destination,
    author: `${["林", "王", "陈", "赵", "李", "周", "吴", "郑"][i % 8]}同学`,
    content,
    image: images[i % images.length],
    tags,
    view: 30 + ((i * 17) % 190),
    rating: (3.7 + ((i * 13) % 13) / 10).toFixed(2),
    ratingCount: 5 + ((i * 7) % 35),
    compressed,
  });
}

const sql = [
  "-- Auto-generated by database/generate_diary_seed.mjs",
  "USE personalized_travel;",
  "TRUNCATE TABLE travel_diary;",
  `INSERT INTO travel_diary
(id, title, destination, author_name, content, image_url, video_url, interest_tags, view_count, rating, rating_count, compressed_content)
VALUES`,
  rows.map((row) => `(${[
    row.id,
    q(row.title),
    q(row.destination),
    q(row.author),
    q(row.content),
    q(row.image),
    q(""),
    q(row.tags),
    row.view,
    row.rating,
    row.ratingCount,
    q(row.compressed),
  ].join(", ")})`).join(",\n") + ";",
  "SELECT COUNT(*) AS diary_count FROM travel_diary;",
].join("\n\n");

const output = path.join(OUT_DIR, "diary_seed_80.sql");
await fs.writeFile(output, sql, "utf8");
console.log(`已生成 travel_diary: ${rows.length}`);
console.log(`输出文件: ${output}`);

function q(value) {
  return `'${String(value ?? "").replaceAll("'", "''")}'`;
}

function unique(items) {
  return Array.from(new Set(items.filter(Boolean)));
}
