#!/usr/bin/env node
/**
 * 生成景区/校园内部地图验收数据。
 *
 * 默认规模：
 * - 200 个 map_area
 * - 每个区域 20 个建筑物/景点 + 50 个服务设施
 * - 每个区域约 100 条内部道路边
 *
 * 输出：
 * - database/generated/area_map_data.sql
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "database", "generated");

const AREA_COUNT = Number(process.env.MAP_AREA_COUNT || 200);
const CORE_NODE_COUNT = Number(process.env.MAP_CORE_NODE_COUNT || 20);
const FACILITY_COUNT = Number(process.env.MAP_FACILITY_COUNT || 50);
const EXTRA_EDGE_COUNT = Number(process.env.MAP_EXTRA_EDGE_COUNT || 30);

const cities = [
  ["成都", "武侯区", 104.061, 30.642],
  ["成都", "青羊区", 104.049, 30.674],
  ["成都", "锦江区", 104.083, 30.651],
  ["成都", "成华区", 104.104, 30.680],
  ["成都", "金牛区", 104.052, 30.705],
  ["杭州", "西湖区", 120.130, 30.259],
  ["西安", "雁塔区", 108.946, 34.214],
  ["重庆", "沙坪坝区", 106.456, 29.562],
];

const scenicNames = ["青竹湖", "云锦山", "锦水古镇", "月影公园", "花溪谷", "栖霞园", "望江岭", "松风湖"];
const campusNames = ["明德大学", "知行学院", "启航大学", "博雅学院", "天府理工", "西岭大学", "锦城学院", "青禾大学"];
const scenicCoreCategories = ["景点", "游客中心", "观景台", "展览馆", "办公楼", "管理处", "文化馆", "入口广场"];
const campusCoreCategories = ["教学楼", "办公楼", "宿舍楼", "实验楼", "体育馆", "图书馆", "报告厅", "学院楼"];
const facilityCategories = [
  "商店",
  "饭店",
  "洗手间",
  "图书馆",
  "食堂",
  "超市",
  "咖啡馆",
  "医务室",
  "停车场",
  "便利店",
  "服务台",
  "饮水点",
];
const roadTypes = ["walkway", "main_road", "greenway", "stairs", "covered_walkway"];

await fs.mkdir(OUT_DIR, { recursive: true });

const areas = [];
const nodes = [];
const edges = [];
let nodeId = 1;
let edgeId = 1;

for (let areaId = 1; areaId <= AREA_COUNT; areaId += 1) {
  const isCampus = areaId % 2 === 0;
  const [city, district, baseLng, baseLat] = cities[areaId % cities.length];
  const areaName = isCampus
    ? `${campusNames[areaId % campusNames.length]}${String(areaId).padStart(3, "0")}校区`
    : `${scenicNames[areaId % scenicNames.length]}${String(areaId).padStart(3, "0")}景区`;
  const centerLng = baseLng + ((areaId % 17) - 8) * 0.006;
  const centerLat = baseLat + ((areaId % 13) - 6) * 0.004;
  areas.push({
    id: areaId,
    name: areaName,
    areaType: isCampus ? "campus" : "scenic",
    city,
    district,
    address: `${district}${areaName}内部道路片区`,
    longitude: centerLng,
    latitude: centerLat,
    description: `${areaName}包含建筑物、服务设施和内部道路，用于路径查询与地图验收数据。`,
  });

  const areaNodeIds = [];
  const coreCategories = isCampus ? campusCoreCategories : scenicCoreCategories;
  for (let i = 0; i < CORE_NODE_COUNT; i += 1) {
    const category = coreCategories[i % coreCategories.length];
    const node = buildNode({
      id: nodeId,
      areaId,
      areaName,
      index: i,
      centerLng,
      centerLat,
      nodeType: category === "景点" ? "scenic" : "building",
      category,
      name: `${areaName}${category}${i + 1}`,
      serviceTags: `${category},核心建筑`,
      description: `${areaName}内部${category}，可作为路线节点。`,
    });
    nodes.push(node);
    areaNodeIds.push(nodeId);
    nodeId += 1;
  }

  for (let i = 0; i < FACILITY_COUNT; i += 1) {
    const category = facilityCategories[i % facilityCategories.length];
    const node = buildNode({
      id: nodeId,
      areaId,
      areaName,
      index: CORE_NODE_COUNT + i,
      centerLng,
      centerLat,
      nodeType: "facility",
      category,
      name: `${areaName}${category}${i + 1}`,
      serviceTags: `${category},服务设施`,
      description: `${areaName}内部${category}，用于补充休息、餐饮、购物和基础服务。`,
    });
    nodes.push(node);
    areaNodeIds.push(nodeId);
    nodeId += 1;
  }

  const createdPairs = new Set();
  for (let i = 0; i < areaNodeIds.length; i += 1) {
    const from = areaNodeIds[i];
    const to = areaNodeIds[(i + 1) % areaNodeIds.length];
    edgeId = addEdge(edges, createdPairs, edgeId, areaId, from, to);
  }

  for (let i = 0; i < EXTRA_EDGE_COUNT; i += 1) {
    const fromIndex = (i * 7 + areaId) % areaNodeIds.length;
    const toIndex = (fromIndex + 5 + (i % 11)) % areaNodeIds.length;
    edgeId = addEdge(edges, createdPairs, edgeId, areaId, areaNodeIds[fromIndex], areaNodeIds[toIndex]);
  }
}

const sql = [
  "-- Auto-generated by database/generate_area_map_data.mjs",
  "-- Data target: map_area / map_node / map_edge",
  "USE personalized_travel;",
  "SET FOREIGN_KEY_CHECKS = 0;",
  "TRUNCATE TABLE map_edge;",
  "TRUNCATE TABLE map_node;",
  "TRUNCATE TABLE map_area;",
  "SET FOREIGN_KEY_CHECKS = 1;",
  buildAreaSql(areas),
  buildNodeSql(nodes),
  buildEdgeSql(edges),
  buildSummarySql(),
].join("\n\n");

const output = path.join(OUT_DIR, "area_map_data.sql");
await fs.writeFile(output, sql, "utf8");

console.log(`已生成 map_area: ${areas.length}`);
console.log(`已生成 map_node: ${nodes.length}`);
console.log(`已生成 map_edge: ${edges.length}`);
console.log(`输出文件: ${output}`);

function buildNode({ id, areaId, areaName, index, centerLng, centerLat, nodeType, category, name, serviceTags, description }) {
  const ring = Math.floor(index / 12) + 1;
  const angle = (index % 12) * (Math.PI / 6) + ring * 0.13;
  const radius = 0.0012 + ring * 0.00042;
  return {
    id,
    areaId,
    name,
    nodeType,
    category,
    longitude: centerLng + Math.cos(angle) * radius,
    latitude: centerLat + Math.sin(angle) * radius,
    floorCount: nodeType === "facility" ? 1 : 2 + (index % 6),
    openTime: nodeType === "facility" ? "08:00" : "07:30",
    closeTime: nodeType === "facility" ? "22:00" : "21:30",
    serviceTags,
    description: description || `${areaName}内部节点`,
  };
}

function addEdge(target, createdPairs, edgeId, areaId, fromNodeId, toNodeId) {
  const from = Math.min(fromNodeId, toNodeId);
  const to = Math.max(fromNodeId, toNodeId);
  const key = `${from}-${to}`;
  if (createdPairs.has(key) || from === to) {
    return edgeId;
  }
  createdPairs.add(key);
  const distance = 60 + ((from * 17 + to * 11) % 260);
  target.push({
    id: edgeId,
    areaId,
    fromNodeId: from,
    toNodeId: to,
    distance,
    travelTime: Math.max(1, Math.round(distance / 75)),
    roadType: roadTypes[(from + to) % roadTypes.length],
  });
  return edgeId + 1;
}

function buildAreaSql(items) {
  return chunkedInsert(
    "map_area",
    ["id", "name", "area_type", "city", "district", "address", "longitude", "latitude", "description"],
    items.map((item) => [
      item.id,
      q(item.name),
      q(item.areaType),
      q(item.city),
      q(item.district),
      q(item.address),
      fixed(item.longitude),
      fixed(item.latitude),
      q(item.description),
    ])
  );
}

function buildNodeSql(items) {
  return chunkedInsert(
    "map_node",
    ["id", "area_id", "name", "node_type", "category", "longitude", "latitude", "floor_count", "open_time", "close_time", "service_tags", "description"],
    items.map((item) => [
      item.id,
      item.areaId,
      q(item.name),
      q(item.nodeType),
      q(item.category),
      fixed(item.longitude),
      fixed(item.latitude),
      item.floorCount,
      q(item.openTime),
      q(item.closeTime),
      q(item.serviceTags),
      q(item.description),
    ]),
    800
  );
}

function buildEdgeSql(items) {
  return chunkedInsert(
    "map_edge",
    ["id", "area_id", "from_node_id", "to_node_id", "distance", "travel_time", "road_type", "bidirectional"],
    items.map((item) => [
      item.id,
      item.areaId,
      item.fromNodeId,
      item.toNodeId,
      item.distance.toFixed(2),
      item.travelTime,
      q(item.roadType),
      1,
    ]),
    1000
  );
}

function chunkedInsert(table, columns, rows, chunkSize = 500) {
  const chunks = [];
  for (let i = 0; i < rows.length; i += chunkSize) {
    const part = rows.slice(i, i + chunkSize)
      .map((row) => `(${row.join(", ")})`)
      .join(",\n");
    chunks.push(`INSERT INTO ${table} (${columns.join(", ")}) VALUES\n${part};`);
  }
  return chunks.join("\n\n");
}

function buildSummarySql() {
  return [
    "-- 验收数量检查",
    "SELECT COUNT(*) AS area_count FROM map_area;",
    "SELECT COUNT(*) AS node_count FROM map_node;",
    "SELECT COUNT(*) AS edge_count FROM map_edge;",
    "SELECT category, COUNT(*) AS count FROM map_node WHERE node_type = 'facility' GROUP BY category ORDER BY count DESC;",
  ].join("\n");
}

function q(value) {
  if (value === null || value === undefined) {
    return "NULL";
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function fixed(value) {
  return Number(value).toFixed(6);
}
